// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeBPCoGMU8NLigK5uVscj8AkPxK7WVrx0',
    appId: '1:79733169452:web:0fdc6e145a53d63098a089',
    messagingSenderId: '79733169452',
    projectId: 'tinder-clone-705a4',
    authDomain: 'tinder-clone-705a4.firebaseapp.com',
    databaseURL: 'https://tinder-clone-705a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinder-clone-705a4.firebasestorage.app',
    measurementId: 'G-T9CGREL91D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE1l93bIfnq15BS_DvUX6-wZTS3uqzgoo',
    appId: '1:79733169452:android:bf1baf8b286b1ff198a089',
    messagingSenderId: '79733169452',
    projectId: 'tinder-clone-705a4',
    databaseURL: 'https://tinder-clone-705a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinder-clone-705a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOBWl_6t4oXeF6YUK5FZ1WiI-HwM5v9R0',
    appId: '1:79733169452:ios:ea4bd2ce0f625cee98a089',
    messagingSenderId: '79733169452',
    projectId: 'tinder-clone-705a4',
    databaseURL: 'https://tinder-clone-705a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinder-clone-705a4.firebasestorage.app',
    iosBundleId: 'com.example.tiki',
  );
}
